package model;

import model.base.BaseCombas;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Combas extends BaseCombas<Combas> {
	public static final Combas dao = new Combas().dao();
}
