package model;

import model.base.BaseIndicator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Indicator extends BaseIndicator<Indicator> {
	public static final Indicator dao = new Indicator().dao();
}
