package model;

import model.base.BaseProfit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Profit extends BaseProfit<Profit> {
	public static final Profit dao = new Profit().dao();
}
