package model;

import model.base.BaseUseViolation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UseViolation extends BaseUseViolation<UseViolation> {
	public static final UseViolation dao = new UseViolation().dao();
}
