package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseViolation<M extends BaseViolation<M>> extends Model<M> implements IBean {

	public void setViolationID(java.lang.String ViolationID) {
		set("ViolationID", ViolationID);
	}

	public java.lang.String getViolationID() {
		return get("ViolationID");
	}

	public void setSymbol(java.lang.String Symbol) {
		set("Symbol", Symbol);
	}

	public java.lang.String getSymbol() {
		return get("Symbol");
	}

	public void setViolationType(java.lang.String ViolationType) {
		set("ViolationType", ViolationType);
	}

	public java.lang.String getViolationType() {
		return get("ViolationType");
	}

	public void setViolationTypeID(java.lang.String ViolationTypeID) {
		set("ViolationTypeID", ViolationTypeID);
	}

	public java.lang.String getViolationTypeID() {
		return get("ViolationTypeID");
	}

	public void setViolationYear(java.lang.String ViolationYear) {
		set("ViolationYear", ViolationYear);
	}

	public java.lang.String getViolationYear() {
		return get("ViolationYear");
	}

	public void setActivity(java.lang.String Activity) {
		set("Activity", Activity);
	}

	public java.lang.String getActivity() {
		return get("Activity");
	}

}
