package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCombas<M extends BaseCombas<M>> extends Model<M> implements IBean {

	public void setStkcd(java.lang.Integer Stkcd) {
		set("Stkcd", Stkcd);
	}

	public java.lang.Integer getStkcd() {
		return get("Stkcd");
	}

	public void setAccper(java.util.Date Accper) {
		set("Accper", Accper);
	}

	public java.util.Date getAccper() {
		return get("Accper");
	}

	public void setTyprep(java.lang.String Typrep) {
		set("Typrep", Typrep);
	}

	public java.lang.String getTyprep() {
		return get("Typrep");
	}

	public void setA001101000(java.lang.Float A001101000) {
		set("A001101000", A001101000);
	}

	public java.lang.Float getA001101000() {
		return get("A001101000");
	}

	public void setA0d1101101(java.lang.String A0d1101101) {
		set("A0d1101101", A0d1101101);
	}

	public java.lang.String getA0d1101101() {
		return get("A0d1101101");
	}

	public void setA0d1102000(java.lang.Long A0d1102000) {
		set("A0d1102000", A0d1102000);
	}

	public java.lang.Long getA0d1102000() {
		return get("A0d1102000");
	}

	public void setA0d1102101(java.lang.String A0d1102101) {
		set("A0d1102101", A0d1102101);
	}

	public java.lang.String getA0d1102101() {
		return get("A0d1102101");
	}

	public void setA0b1103000(java.lang.String A0b1103000) {
		set("A0b1103000", A0b1103000);
	}

	public java.lang.String getA0b1103000() {
		return get("A0b1103000");
	}

	public void setA0b1104000(java.lang.Float A0b1104000) {
		set("A0b1104000", A0b1104000);
	}

	public java.lang.Float getA0b1104000() {
		return get("A0b1104000");
	}

	public void setA0b1105000(java.lang.String A0b1105000) {
		set("A0b1105000", A0b1105000);
	}

	public java.lang.String getA0b1105000() {
		return get("A0b1105000");
	}

	public void setA0f1106000(java.lang.Float A0f1106000) {
		set("A0f1106000", A0f1106000);
	}

	public java.lang.Float getA0f1106000() {
		return get("A0f1106000");
	}

	public void setA001107000(java.lang.Float A001107000) {
		set("A001107000", A001107000);
	}

	public java.lang.Float getA001107000() {
		return get("A001107000");
	}

	public void setA0f1108000(java.lang.Float A0f1108000) {
		set("A0f1108000", A0f1108000);
	}

	public java.lang.Float getA0f1108000() {
		return get("A0f1108000");
	}

	public void setA001109000(java.lang.String A001109000) {
		set("A001109000", A001109000);
	}

	public java.lang.String getA001109000() {
		return get("A001109000");
	}

	public void setA001110000(java.lang.String A001110000) {
		set("A001110000", A001110000);
	}

	public java.lang.String getA001110000() {
		return get("A001110000");
	}

	public void setA001111000(java.lang.String A001111000) {
		set("A001111000", A001111000);
	}

	public java.lang.String getA001111000() {
		return get("A001111000");
	}

	public void setA001112000(java.lang.String A001112000) {
		set("A001112000", A001112000);
	}

	public java.lang.String getA001112000() {
		return get("A001112000");
	}

	public void setA0i1113000(java.lang.String A0i1113000) {
		set("A0i1113000", A0i1113000);
	}

	public java.lang.String getA0i1113000() {
		return get("A0i1113000");
	}

	public void setA0i1114000(java.lang.String A0i1114000) {
		set("A0i1114000", A0i1114000);
	}

	public java.lang.String getA0i1114000() {
		return get("A0i1114000");
	}

	public void setA0i1115000(java.lang.String A0i1115000) {
		set("A0i1115000", A0i1115000);
	}

	public java.lang.String getA0i1115000() {
		return get("A0i1115000");
	}

	public void setA0i1116000(java.lang.Long A0i1116000) {
		set("A0i1116000", A0i1116000);
	}

	public java.lang.Long getA0i1116000() {
		return get("A0i1116000");
	}

	public void setA0i1116101(java.lang.String A0i1116101) {
		set("A0i1116101", A0i1116101);
	}

	public java.lang.String getA0i1116101() {
		return get("A0i1116101");
	}

	public void setA0i1116201(java.lang.String A0i1116201) {
		set("A0i1116201", A0i1116201);
	}

	public java.lang.String getA0i1116201() {
		return get("A0i1116201");
	}

	public void setA0i1116301(java.lang.String A0i1116301) {
		set("A0i1116301", A0i1116301);
	}

	public java.lang.String getA0i1116301() {
		return get("A0i1116301");
	}

	public void setA0i1116401(java.lang.String A0i1116401) {
		set("A0i1116401", A0i1116401);
	}

	public java.lang.String getA0i1116401() {
		return get("A0i1116401");
	}

	public void setA001119000(java.lang.Float A001119000) {
		set("A001119000", A001119000);
	}

	public java.lang.Float getA001119000() {
		return get("A001119000");
	}

	public void setA001120000(java.lang.Long A001120000) {
		set("A001120000", A001120000);
	}

	public java.lang.Long getA001120000() {
		return get("A001120000");
	}

	public void setA001121000(java.lang.Float A001121000) {
		set("A001121000", A001121000);
	}

	public java.lang.Float getA001121000() {
		return get("A001121000");
	}

	public void setA0f1122000(java.lang.Long A0f1122000) {
		set("A0f1122000", A0f1122000);
	}

	public java.lang.Long getA0f1122000() {
		return get("A0f1122000");
	}

	public void setA001123000(java.lang.String A001123000) {
		set("A001123000", A001123000);
	}

	public java.lang.String getA001123000() {
		return get("A001123000");
	}

	public void setA001124000(java.lang.String A001124000) {
		set("A001124000", A001124000);
	}

	public java.lang.String getA001124000() {
		return get("A001124000");
	}

	public void setA0d1126000(java.lang.String A0d1126000) {
		set("A0d1126000", A0d1126000);
	}

	public java.lang.String getA0d1126000() {
		return get("A0d1126000");
	}

	public void setA001125000(java.lang.String A001125000) {
		set("A001125000", A001125000);
	}

	public java.lang.String getA001125000() {
		return get("A001125000");
	}

	public void setA001100000(java.lang.String A001100000) {
		set("A001100000", A001100000);
	}

	public java.lang.String getA001100000() {
		return get("A001100000");
	}

	public void setA0i1224000(java.lang.String A0i1224000) {
		set("A0i1224000", A0i1224000);
	}

	public java.lang.String getA0i1224000() {
		return get("A0i1224000");
	}

	public void setA0i1225000(java.lang.String A0i1225000) {
		set("A0i1225000", A0i1225000);
	}

	public java.lang.String getA0i1225000() {
		return get("A0i1225000");
	}

	public void setA0b1201000(java.lang.Float A0b1201000) {
		set("A0b1201000", A0b1201000);
	}

	public java.lang.Float getA0b1201000() {
		return get("A0b1201000");
	}

	public void setA001202000(java.lang.Float A001202000) {
		set("A001202000", A001202000);
	}

	public java.lang.Float getA001202000() {
		return get("A001202000");
	}

	public void setA001203000(java.lang.String A001203000) {
		set("A001203000", A001203000);
	}

	public java.lang.String getA001203000() {
		return get("A001203000");
	}

	public void setA001204000(java.lang.String A001204000) {
		set("A001204000", A001204000);
	}

	public java.lang.String getA001204000() {
		return get("A001204000");
	}

	public void setA001205000(java.lang.Float A001205000) {
		set("A001205000", A001205000);
	}

	public java.lang.Float getA001205000() {
		return get("A001205000");
	}

	public void setA001206000(java.lang.String A001206000) {
		set("A001206000", A001206000);
	}

	public java.lang.String getA001206000() {
		return get("A001206000");
	}

	public void setA001207000(java.lang.String A001207000) {
		set("A001207000", A001207000);
	}

	public java.lang.String getA001207000() {
		return get("A001207000");
	}

	public void setA0i1209000(java.lang.String A0i1209000) {
		set("A0i1209000", A0i1209000);
	}

	public java.lang.String getA0i1209000() {
		return get("A0i1209000");
	}

	public void setA0i1210000(java.lang.String A0i1210000) {
		set("A0i1210000", A0i1210000);
	}

	public java.lang.String getA0i1210000() {
		return get("A0i1210000");
	}

	public void setA001211000(java.lang.String A001211000) {
		set("A001211000", A001211000);
	}

	public java.lang.String getA001211000() {
		return get("A001211000");
	}

	public void setA001212000(java.lang.Float A001212000) {
		set("A001212000", A001212000);
	}

	public java.lang.Float getA001212000() {
		return get("A001212000");
	}

	public void setA001213000(java.lang.Float A001213000) {
		set("A001213000", A001213000);
	}

	public java.lang.Float getA001213000() {
		return get("A001213000");
	}

	public void setA001214000(java.lang.String A001214000) {
		set("A001214000", A001214000);
	}

	public java.lang.String getA001214000() {
		return get("A001214000");
	}

	public void setA001215000(java.lang.Float A001215000) {
		set("A001215000", A001215000);
	}

	public java.lang.Float getA001215000() {
		return get("A001215000");
	}

	public void setA001216000(java.lang.String A001216000) {
		set("A001216000", A001216000);
	}

	public java.lang.String getA001216000() {
		return get("A001216000");
	}

	public void setA001217000(java.lang.String A001217000) {
		set("A001217000", A001217000);
	}

	public java.lang.String getA001217000() {
		return get("A001217000");
	}

	public void setA001218000(java.lang.Float A001218000) {
		set("A001218000", A001218000);
	}

	public java.lang.Float getA001218000() {
		return get("A001218000");
	}

	public void setA0d1218101(java.lang.String A0d1218101) {
		set("A0d1218101", A0d1218101);
	}

	public java.lang.String getA0d1218101() {
		return get("A0d1218101");
	}

	public void setA001219000(java.lang.String A001219000) {
		set("A001219000", A001219000);
	}

	public java.lang.String getA001219000() {
		return get("A001219000");
	}

	public void setA001220000(java.lang.String A001220000) {
		set("A001220000", A001220000);
	}

	public java.lang.String getA001220000() {
		return get("A001220000");
	}

	public void setA001221000(java.lang.Float A001221000) {
		set("A001221000", A001221000);
	}

	public java.lang.Float getA001221000() {
		return get("A001221000");
	}

	public void setA001222000(java.lang.Float A001222000) {
		set("A001222000", A001222000);
	}

	public java.lang.Float getA001222000() {
		return get("A001222000");
	}

	public void setA001223000(java.lang.String A001223000) {
		set("A001223000", A001223000);
	}

	public java.lang.String getA001223000() {
		return get("A001223000");
	}

	public void setA001200000(java.lang.String A001200000) {
		set("A001200000", A001200000);
	}

	public java.lang.String getA001200000() {
		return get("A001200000");
	}

	public void setA0f1300000(java.lang.Float A0f1300000) {
		set("A0f1300000", A0f1300000);
	}

	public java.lang.Float getA0f1300000() {
		return get("A0f1300000");
	}

	public void setA001000000(java.lang.Float A001000000) {
		set("A001000000", A001000000);
	}

	public java.lang.Float getA001000000() {
		return get("A001000000");
	}

	public void setA002101000(java.lang.Long A002101000) {
		set("A002101000", A002101000);
	}

	public java.lang.Long getA002101000() {
		return get("A002101000");
	}

	public void setA0d2101101(java.lang.String A0d2101101) {
		set("A0d2101101", A0d2101101);
	}

	public java.lang.String getA0d2101101() {
		return get("A0d2101101");
	}

	public void setA0b2102000(java.lang.Long A0b2102000) {
		set("A0b2102000", A0b2102000);
	}

	public java.lang.Long getA0b2102000() {
		return get("A0b2102000");
	}

	public void setA0b2103000(java.lang.Float A0b2103000) {
		set("A0b2103000", A0b2103000);
	}

	public java.lang.Float getA0b2103000() {
		return get("A0b2103000");
	}

	public void setA0b2103101(java.lang.Float A0b2103101) {
		set("A0b2103101", A0b2103101);
	}

	public java.lang.Float getA0b2103101() {
		return get("A0b2103101");
	}

	public void setA0b2103201(java.lang.Float A0b2103201) {
		set("A0b2103201", A0b2103201);
	}

	public java.lang.Float getA0b2103201() {
		return get("A0b2103201");
	}

	public void setA0f2104000(java.lang.Long A0f2104000) {
		set("A0f2104000", A0f2104000);
	}

	public java.lang.Long getA0f2104000() {
		return get("A0f2104000");
	}

	public void setA002105000(java.lang.String A002105000) {
		set("A002105000", A002105000);
	}

	public java.lang.String getA002105000() {
		return get("A002105000");
	}

	public void setA0f2106000(java.lang.Float A0f2106000) {
		set("A0f2106000", A0f2106000);
	}

	public java.lang.Float getA0f2106000() {
		return get("A0f2106000");
	}

	public void setA002107000(java.lang.String A002107000) {
		set("A002107000", A002107000);
	}

	public java.lang.String getA002107000() {
		return get("A002107000");
	}

	public void setA002108000(java.lang.String A002108000) {
		set("A002108000", A002108000);
	}

	public java.lang.String getA002108000() {
		return get("A002108000");
	}

	public void setA002109000(java.lang.String A002109000) {
		set("A002109000", A002109000);
	}

	public java.lang.String getA002109000() {
		return get("A002109000");
	}

	public void setA0f2110000(java.lang.Float A0f2110000) {
		set("A0f2110000", A0f2110000);
	}

	public java.lang.Float getA0f2110000() {
		return get("A0f2110000");
	}

	public void setA0i2111000(java.lang.String A0i2111000) {
		set("A0i2111000", A0i2111000);
	}

	public java.lang.String getA0i2111000() {
		return get("A0i2111000");
	}

	public void setA002112000(java.lang.Float A002112000) {
		set("A002112000", A002112000);
	}

	public java.lang.Float getA002112000() {
		return get("A002112000");
	}

	public void setA002113000(java.lang.Float A002113000) {
		set("A002113000", A002113000);
	}

	public java.lang.Float getA002113000() {
		return get("A002113000");
	}

	public void setA002114000(java.lang.Float A002114000) {
		set("A002114000", A002114000);
	}

	public java.lang.Float getA002114000() {
		return get("A002114000");
	}

	public void setA002115000(java.lang.Float A002115000) {
		set("A002115000", A002115000);
	}

	public java.lang.Float getA002115000() {
		return get("A002115000");
	}

	public void setA0i2116000(java.lang.String A0i2116000) {
		set("A0i2116000", A0i2116000);
	}

	public java.lang.String getA0i2116000() {
		return get("A0i2116000");
	}

	public void setA0i2117000(java.lang.String A0i2117000) {
		set("A0i2117000", A0i2117000);
	}

	public java.lang.String getA0i2117000() {
		return get("A0i2117000");
	}

	public void setA0i2118000(java.lang.String A0i2118000) {
		set("A0i2118000", A0i2118000);
	}

	public java.lang.String getA0i2118000() {
		return get("A0i2118000");
	}

	public void setA0i2119000(java.lang.Long A0i2119000) {
		set("A0i2119000", A0i2119000);
	}

	public java.lang.Long getA0i2119000() {
		return get("A0i2119000");
	}

	public void setA0i2119101(java.lang.String A0i2119101) {
		set("A0i2119101", A0i2119101);
	}

	public java.lang.String getA0i2119101() {
		return get("A0i2119101");
	}

	public void setA0i2119201(java.lang.String A0i2119201) {
		set("A0i2119201", A0i2119201);
	}

	public java.lang.String getA0i2119201() {
		return get("A0i2119201");
	}

	public void setA0i2119301(java.lang.String A0i2119301) {
		set("A0i2119301", A0i2119301);
	}

	public java.lang.String getA0i2119301() {
		return get("A0i2119301");
	}

	public void setA0i2119401(java.lang.String A0i2119401) {
		set("A0i2119401", A0i2119401);
	}

	public java.lang.String getA0i2119401() {
		return get("A0i2119401");
	}

	public void setA002120000(java.lang.Float A002120000) {
		set("A002120000", A002120000);
	}

	public java.lang.Float getA002120000() {
		return get("A002120000");
	}

	public void setA0i2121000(java.lang.String A0i2121000) {
		set("A0i2121000", A0i2121000);
	}

	public java.lang.String getA0i2121000() {
		return get("A0i2121000");
	}

	public void setA0d2122000(java.lang.String A0d2122000) {
		set("A0d2122000", A0d2122000);
	}

	public java.lang.String getA0d2122000() {
		return get("A0d2122000");
	}

	public void setA0d2123000(java.lang.String A0d2123000) {
		set("A0d2123000", A0d2123000);
	}

	public java.lang.String getA0d2123000() {
		return get("A0d2123000");
	}

	public void setA0i2124000(java.lang.String A0i2124000) {
		set("A0i2124000", A0i2124000);
	}

	public java.lang.String getA0i2124000() {
		return get("A0i2124000");
	}

	public void setA002125000(java.lang.String A002125000) {
		set("A002125000", A002125000);
	}

	public java.lang.String getA002125000() {
		return get("A002125000");
	}

	public void setA002126000(java.lang.String A002126000) {
		set("A002126000", A002126000);
	}

	public java.lang.String getA002126000() {
		return get("A002126000");
	}

	public void setA002127000(java.lang.String A002127000) {
		set("A002127000", A002127000);
	}

	public java.lang.String getA002127000() {
		return get("A002127000");
	}

	public void setA002100000(java.lang.String A002100000) {
		set("A002100000", A002100000);
	}

	public java.lang.String getA002100000() {
		return get("A002100000");
	}

	public void setA002201000(java.lang.String A002201000) {
		set("A002201000", A002201000);
	}

	public java.lang.String getA002201000() {
		return get("A002201000");
	}

	public void setA0d2202000(java.lang.String A0d2202000) {
		set("A0d2202000", A0d2202000);
	}

	public java.lang.String getA0d2202000() {
		return get("A0d2202000");
	}

	public void setA002203000(java.lang.Long A002203000) {
		set("A002203000", A002203000);
	}

	public java.lang.Long getA002203000() {
		return get("A002203000");
	}

	public void setA002204000(java.lang.Long A002204000) {
		set("A002204000", A002204000);
	}

	public java.lang.Long getA002204000() {
		return get("A002204000");
	}

	public void setA002205000(java.lang.String A002205000) {
		set("A002205000", A002205000);
	}

	public java.lang.String getA002205000() {
		return get("A002205000");
	}

	public void setA002206000(java.lang.Long A002206000) {
		set("A002206000", A002206000);
	}

	public java.lang.Long getA002206000() {
		return get("A002206000");
	}

	public void setA002207000(java.lang.String A002207000) {
		set("A002207000", A002207000);
	}

	public java.lang.String getA002207000() {
		return get("A002207000");
	}

	public void setA002208000(java.lang.String A002208000) {
		set("A002208000", A002208000);
	}

	public java.lang.String getA002208000() {
		return get("A002208000");
	}

	public void setA002209000(java.lang.String A002209000) {
		set("A002209000", A002209000);
	}

	public java.lang.String getA002209000() {
		return get("A002209000");
	}

	public void setA002210000(java.lang.String A002210000) {
		set("A002210000", A002210000);
	}

	public java.lang.String getA002210000() {
		return get("A002210000");
	}

	public void setA002200000(java.lang.String A002200000) {
		set("A002200000", A002200000);
	}

	public java.lang.String getA002200000() {
		return get("A002200000");
	}

	public void setA0f2300000(java.lang.Float A0f2300000) {
		set("A0f2300000", A0f2300000);
	}

	public java.lang.Float getA0f2300000() {
		return get("A0f2300000");
	}

	public void setA002000000(java.lang.Float A002000000) {
		set("A002000000", A002000000);
	}

	public java.lang.Float getA002000000() {
		return get("A002000000");
	}

	public void setA003101000(java.lang.Long A003101000) {
		set("A003101000", A003101000);
	}

	public java.lang.Long getA003101000() {
		return get("A003101000");
	}

	public void setA003112000(java.lang.String A003112000) {
		set("A003112000", A003112000);
	}

	public java.lang.String getA003112000() {
		return get("A003112000");
	}

	public void setA003112101(java.lang.String A003112101) {
		set("A003112101", A003112101);
	}

	public java.lang.String getA003112101() {
		return get("A003112101");
	}

	public void setA003112201(java.lang.String A003112201) {
		set("A003112201", A003112201);
	}

	public java.lang.String getA003112201() {
		return get("A003112201");
	}

	public void setA003112301(java.lang.String A003112301) {
		set("A003112301", A003112301);
	}

	public java.lang.String getA003112301() {
		return get("A003112301");
	}

	public void setA003102000(java.lang.Float A003102000) {
		set("A003102000", A003102000);
	}

	public java.lang.Float getA003102000() {
		return get("A003102000");
	}

	public void setA003102101(java.lang.String A003102101) {
		set("A003102101", A003102101);
	}

	public java.lang.String getA003102101() {
		return get("A003102101");
	}

	public void setA003103000(java.lang.Float A003103000) {
		set("A003103000", A003103000);
	}

	public java.lang.Float getA003103000() {
		return get("A003103000");
	}

	public void setA0f3104000(java.lang.Long A0f3104000) {
		set("A0f3104000", A0f3104000);
	}

	public java.lang.Long getA0f3104000() {
		return get("A0f3104000");
	}

	public void setA003105000(java.lang.Float A003105000) {
		set("A003105000", A003105000);
	}

	public java.lang.Float getA003105000() {
		return get("A003105000");
	}

	public void setA003106000(java.lang.String A003106000) {
		set("A003106000", A003106000);
	}

	public java.lang.String getA003106000() {
		return get("A003106000");
	}

	public void setA003107000(java.lang.String A003107000) {
		set("A003107000", A003107000);
	}

	public java.lang.String getA003107000() {
		return get("A003107000");
	}

	public void setA0F3108000(java.lang.String A0F3108000) {
		set("A0F3108000", A0F3108000);
	}

	public java.lang.String getA0F3108000() {
		return get("A0F3108000");
	}

	public void setA0F3109000(java.lang.String A0F3109000) {
		set("A0F3109000", A0F3109000);
	}

	public java.lang.String getA0F3109000() {
		return get("A0F3109000");
	}

	public void setA003111000(java.lang.String A003111000) {
		set("A003111000", A003111000);
	}

	public java.lang.String getA003111000() {
		return get("A003111000");
	}

	public void setA003100000(java.lang.Float A003100000) {
		set("A003100000", A003100000);
	}

	public java.lang.Float getA003100000() {
		return get("A003100000");
	}

	public void setA003200000(java.lang.String A003200000) {
		set("A003200000", A003200000);
	}

	public java.lang.String getA003200000() {
		return get("A003200000");
	}

	public void setA003000000(java.lang.Float A003000000) {
		set("A003000000", A003000000);
	}

	public java.lang.Float getA003000000() {
		return get("A003000000");
	}

	public void setA004000000(java.lang.Float A004000000) {
		set("A004000000", A004000000);
	}

	public java.lang.Float getA004000000() {
		return get("A004000000");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

}
