package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIndicator<M extends BaseIndicator<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSymbol(java.lang.Integer symbol) {
		set("symbol", symbol);
	}

	public java.lang.Integer getSymbol() {
		return get("symbol");
	}

	public void setYear(java.lang.Integer year) {
		set("year", year);
	}

	public java.lang.Integer getYear() {
		return get("year");
	}

	public void setDEBTEQ(java.lang.Double DEBTEQ) {
		set("DEBTEQ", DEBTEQ);
	}

	public java.lang.Double getDEBTEQ() {
		return get("DEBTEQ");
	}

	public void setSALTA(java.lang.Double SALTA) {
		set("SALTA", SALTA);
	}

	public java.lang.Double getSALTA() {
		return get("SALTA");
	}

	public void setNPSAL(java.lang.Double NPSAL) {
		set("NPSAL", NPSAL);
	}

	public java.lang.Double getNPSAL() {
		return get("NPSAL");
	}

	public void setRECSAL(java.lang.Double RECSAL) {
		set("RECSAL", RECSAL);
	}

	public java.lang.Double getRECSAL() {
		return get("RECSAL");
	}

	public void setNFATA(java.lang.Double NFATA) {
		set("NFATA", NFATA);
	}

	public java.lang.Double getNFATA() {
		return get("NFATA");
	}

	public void setRETREND(java.lang.Double RETREND) {
		set("RETREND", RETREND);
	}

	public java.lang.Double getRETREND() {
		return get("RETREND");
	}

	public void setGMTREND(java.lang.Double GMTREND) {
		set("GMTREND", GMTREND);
	}

	public java.lang.Double getGMTREND() {
		return get("GMTREND");
	}

	public void setSALGRTH(java.lang.Double SALGRTH) {
		set("SALGRTH", SALGRTH);
	}

	public java.lang.Double getSALGRTH() {
		return get("SALGRTH");
	}

	public void setINVTA(java.lang.Double INVTA) {
		set("INVTA", INVTA);
	}

	public java.lang.Double getINVTA() {
		return get("INVTA");
	}

	public void setCASHTA(java.lang.Double CASHTA) {
		set("CASHTA", CASHTA);
	}

	public java.lang.Double getCASHTA() {
		return get("CASHTA");
	}

	public void setLTA(java.lang.Double LTA) {
		set("LTA", LTA);
	}

	public java.lang.Double getLTA() {
		return get("LTA");
	}

	public void setLOGDEBT(java.lang.Double LOGDEBT) {
		set("LOGDEBT", LOGDEBT);
	}

	public java.lang.Double getLOGDEBT() {
		return get("LOGDEBT");
	}

	public void setCOSAL(java.lang.Double COSAL) {
		set("COSAL", COSAL);
	}

	public java.lang.Double getCOSAL() {
		return get("COSAL");
	}

	public void setEBIT(java.lang.Double EBIT) {
		set("EBIT", EBIT);
	}

	public java.lang.Double getEBIT() {
		return get("EBIT");
	}

	public void setWCAP(java.lang.Double WCAP) {
		set("WCAP", WCAP);
	}

	public java.lang.Double getWCAP() {
		return get("WCAP");
	}

	public void setNIFA(java.lang.Double NIFA) {
		set("NIFA", NIFA);
	}

	public java.lang.Double getNIFA() {
		return get("NIFA");
	}

	public void setTDTA(java.lang.Double TDTA) {
		set("TDTA", TDTA);
	}

	public java.lang.Double getTDTA() {
		return get("TDTA");
	}

	public void setNPTA(java.lang.Double NPTA) {
		set("NPTA", NPTA);
	}

	public java.lang.Double getNPTA() {
		return get("NPTA");
	}

	public void setCACL(java.lang.Double CACL) {
		set("CACL", CACL);
	}

	public java.lang.Double getCACL() {
		return get("CACL");
	}

	public void setWCTA(java.lang.Double WCTA) {
		set("WCTA", WCTA);
	}

	public java.lang.Double getWCTA() {
		return get("WCTA");
	}

	public void setQACL(java.lang.Double QACL) {
		set("QACL", QACL);
	}

	public java.lang.Double getQACL() {
		return get("QACL");
	}

	public void setGPTA(java.lang.Double GPTA) {
		set("GPTA", GPTA);
	}

	public java.lang.Double getGPTA() {
		return get("GPTA");
	}

	public void setLTDTA(java.lang.Double LTDTA) {
		set("LTDTA", LTDTA);
	}

	public java.lang.Double getLTDTA() {
		return get("LTDTA");
	}

}
