package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfit<M extends BaseProfit<M>> extends Model<M> implements IBean {

	public void setStkcd(java.lang.String Stkcd) {
		set("Stkcd", Stkcd);
	}

	public java.lang.String getStkcd() {
		return get("Stkcd");
	}

	public void setAccper(java.lang.String Accper) {
		set("Accper", Accper);
	}

	public java.lang.String getAccper() {
		return get("Accper");
	}

	public void setTyprep(java.lang.String Typrep) {
		set("Typrep", Typrep);
	}

	public java.lang.String getTyprep() {
		return get("Typrep");
	}

	public void setB001100000(java.lang.String B001100000) {
		set("B001100000", B001100000);
	}

	public java.lang.String getB001100000() {
		return get("B001100000");
	}

	public void setB001101000(java.lang.String B001101000) {
		set("B001101000", B001101000);
	}

	public java.lang.String getB001101000() {
		return get("B001101000");
	}

	public void setBbd1102000(java.lang.String Bbd1102000) {
		set("Bbd1102000", Bbd1102000);
	}

	public java.lang.String getBbd1102000() {
		return get("Bbd1102000");
	}

	public void setBbd1102101(java.lang.String Bbd1102101) {
		set("Bbd1102101", Bbd1102101);
	}

	public java.lang.String getBbd1102101() {
		return get("Bbd1102101");
	}

	public void setBbd1102203(java.lang.String Bbd1102203) {
		set("Bbd1102203", Bbd1102203);
	}

	public java.lang.String getBbd1102203() {
		return get("Bbd1102203");
	}

	public void setB0i1103000(java.lang.String B0i1103000) {
		set("B0i1103000", B0i1103000);
	}

	public java.lang.String getB0i1103000() {
		return get("B0i1103000");
	}

	public void setB0i1103101(java.lang.String B0i1103101) {
		set("B0i1103101", B0i1103101);
	}

	public java.lang.String getB0i1103101() {
		return get("B0i1103101");
	}

	public void setB0i1103111(java.lang.String B0i1103111) {
		set("B0i1103111", B0i1103111);
	}

	public java.lang.String getB0i1103111() {
		return get("B0i1103111");
	}

	public void setB0i1103203(java.lang.String B0i1103203) {
		set("B0i1103203", B0i1103203);
	}

	public java.lang.String getB0i1103203() {
		return get("B0i1103203");
	}

	public void setB0i1103303(java.lang.String B0i1103303) {
		set("B0i1103303", B0i1103303);
	}

	public java.lang.String getB0i1103303() {
		return get("B0i1103303");
	}

	public void setB0d1104000(java.lang.String B0d1104000) {
		set("B0d1104000", B0d1104000);
	}

	public java.lang.String getB0d1104000() {
		return get("B0d1104000");
	}

	public void setB0d1104101(java.lang.String B0d1104101) {
		set("B0d1104101", B0d1104101);
	}

	public java.lang.String getB0d1104101() {
		return get("B0d1104101");
	}

	public void setB0d1104201(java.lang.String B0d1104201) {
		set("B0d1104201", B0d1104201);
	}

	public java.lang.String getB0d1104201() {
		return get("B0d1104201");
	}

	public void setB0d1104301(java.lang.String B0d1104301) {
		set("B0d1104301", B0d1104301);
	}

	public java.lang.String getB0d1104301() {
		return get("B0d1104301");
	}

	public void setB0d1104401(java.lang.String B0d1104401) {
		set("B0d1104401", B0d1104401);
	}

	public java.lang.String getB0d1104401() {
		return get("B0d1104401");
	}

	public void setB0d1104501(java.lang.String B0d1104501) {
		set("B0d1104501", B0d1104501);
	}

	public java.lang.String getB0d1104501() {
		return get("B0d1104501");
	}

	public void setB0f1105000(java.lang.String B0f1105000) {
		set("B0f1105000", B0f1105000);
	}

	public java.lang.String getB0f1105000() {
		return get("B0f1105000");
	}

	public void setB001200000(java.lang.String B001200000) {
		set("B001200000", B001200000);
	}

	public java.lang.String getB001200000() {
		return get("B001200000");
	}

	public void setB001201000(java.lang.String B001201000) {
		set("B001201000", B001201000);
	}

	public java.lang.String getB001201000() {
		return get("B001201000");
	}

	public void setB0i1202000(java.lang.String B0i1202000) {
		set("B0i1202000", B0i1202000);
	}

	public java.lang.String getB0i1202000() {
		return get("B0i1202000");
	}

	public void setB0i1203000(java.lang.String B0i1203000) {
		set("B0i1203000", B0i1203000);
	}

	public java.lang.String getB0i1203000() {
		return get("B0i1203000");
	}

	public void setB0i1203101(java.lang.String B0i1203101) {
		set("B0i1203101", B0i1203101);
	}

	public java.lang.String getB0i1203101() {
		return get("B0i1203101");
	}

	public void setB0i1203203(java.lang.String B0i1203203) {
		set("B0i1203203", B0i1203203);
	}

	public java.lang.String getB0i1203203() {
		return get("B0i1203203");
	}

	public void setB0i1204000(java.lang.String B0i1204000) {
		set("B0i1204000", B0i1204000);
	}

	public java.lang.String getB0i1204000() {
		return get("B0i1204000");
	}

	public void setB0i1204101(java.lang.String B0i1204101) {
		set("B0i1204101", B0i1204101);
	}

	public java.lang.String getB0i1204101() {
		return get("B0i1204101");
	}

	public void setB0i1204203(java.lang.String B0i1204203) {
		set("B0i1204203", B0i1204203);
	}

	public java.lang.String getB0i1204203() {
		return get("B0i1204203");
	}

	public void setB0i1205000(java.lang.String B0i1205000) {
		set("B0i1205000", B0i1205000);
	}

	public java.lang.String getB0i1205000() {
		return get("B0i1205000");
	}

	public void setB0i1206000(java.lang.String B0i1206000) {
		set("B0i1206000", B0i1206000);
	}

	public java.lang.String getB0i1206000() {
		return get("B0i1206000");
	}

	public void setB001207000(java.lang.String B001207000) {
		set("B001207000", B001207000);
	}

	public java.lang.String getB001207000() {
		return get("B001207000");
	}

	public void setB0f1208000(java.lang.String B0f1208000) {
		set("B0f1208000", B0f1208000);
	}

	public java.lang.String getB0f1208000() {
		return get("B0f1208000");
	}

	public void setB0i1208103(java.lang.String B0i1208103) {
		set("B0i1208103", B0i1208103);
	}

	public java.lang.String getB0i1208103() {
		return get("B0i1208103");
	}

	public void setB001209000(java.lang.String B001209000) {
		set("B001209000", B001209000);
	}

	public java.lang.String getB001209000() {
		return get("B001209000");
	}

	public void setB001210000(java.lang.String B001210000) {
		set("B001210000", B001210000);
	}

	public java.lang.String getB001210000() {
		return get("B001210000");
	}

	public void setB001211000(java.lang.String B001211000) {
		set("B001211000", B001211000);
	}

	public java.lang.String getB001211000() {
		return get("B001211000");
	}

	public void setB001212000(java.lang.String B001212000) {
		set("B001212000", B001212000);
	}

	public java.lang.String getB001212000() {
		return get("B001212000");
	}

	public void setB0f1213000(java.lang.String B0f1213000) {
		set("B0f1213000", B0f1213000);
	}

	public java.lang.String getB0f1213000() {
		return get("B0f1213000");
	}

	public void setB001301000(java.lang.String B001301000) {
		set("B001301000", B001301000);
	}

	public java.lang.String getB001301000() {
		return get("B001301000");
	}

	public void setB001302000(java.lang.String B001302000) {
		set("B001302000", B001302000);
	}

	public java.lang.String getB001302000() {
		return get("B001302000");
	}

	public void setB001302101(java.lang.String B001302101) {
		set("B001302101", B001302101);
	}

	public java.lang.String getB001302101() {
		return get("B001302101");
	}

	public void setB001303000(java.lang.String B001303000) {
		set("B001303000", B001303000);
	}

	public java.lang.String getB001303000() {
		return get("B001303000");
	}

	public void setB001304000(java.lang.String B001304000) {
		set("B001304000", B001304000);
	}

	public java.lang.String getB001304000() {
		return get("B001304000");
	}

	public void setB001300000(java.lang.String B001300000) {
		set("B001300000", B001300000);
	}

	public java.lang.String getB001300000() {
		return get("B001300000");
	}

	public void setB001400000(java.lang.String B001400000) {
		set("B001400000", B001400000);
	}

	public java.lang.String getB001400000() {
		return get("B001400000");
	}

	public void setB001400101(java.lang.String B001400101) {
		set("B001400101", B001400101);
	}

	public java.lang.String getB001400101() {
		return get("B001400101");
	}

	public void setB001500000(java.lang.String B001500000) {
		set("B001500000", B001500000);
	}

	public java.lang.String getB001500000() {
		return get("B001500000");
	}

	public void setB001500101(java.lang.String B001500101) {
		set("B001500101", B001500101);
	}

	public java.lang.String getB001500101() {
		return get("B001500101");
	}

	public void setB001500201(java.lang.String B001500201) {
		set("B001500201", B001500201);
	}

	public java.lang.String getB001500201() {
		return get("B001500201");
	}

	public void setB001000000(java.lang.String B001000000) {
		set("B001000000", B001000000);
	}

	public java.lang.String getB001000000() {
		return get("B001000000");
	}

	public void setB002100000(java.lang.String B002100000) {
		set("B002100000", B002100000);
	}

	public java.lang.String getB002100000() {
		return get("B002100000");
	}

	public void setB002200000(java.lang.String B002200000) {
		set("B002200000", B002200000);
	}

	public java.lang.String getB002200000() {
		return get("B002200000");
	}

	public void setB002300000(java.lang.String B002300000) {
		set("B002300000", B002300000);
	}

	public java.lang.String getB002300000() {
		return get("B002300000");
	}

	public void setB002000000(java.lang.String B002000000) {
		set("B002000000", B002000000);
	}

	public java.lang.String getB002000000() {
		return get("B002000000");
	}

	public void setB002000101(java.lang.String B002000101) {
		set("B002000101", B002000101);
	}

	public java.lang.String getB002000101() {
		return get("B002000101");
	}

	public void setB002000201(java.lang.String B002000201) {
		set("B002000201", B002000201);
	}

	public java.lang.String getB002000201() {
		return get("B002000201");
	}

	public void setB003000000(java.lang.String B003000000) {
		set("B003000000", B003000000);
	}

	public java.lang.String getB003000000() {
		return get("B003000000");
	}

	public void setB004000000(java.lang.String B004000000) {
		set("B004000000", B004000000);
	}

	public java.lang.String getB004000000() {
		return get("B004000000");
	}

	public void setB005000000(java.lang.String B005000000) {
		set("B005000000", B005000000);
	}

	public java.lang.String getB005000000() {
		return get("B005000000");
	}

	public void setB006000000(java.lang.String B006000000) {
		set("B006000000", B006000000);
	}

	public java.lang.String getB006000000() {
		return get("B006000000");
	}

	public void setB006000101(java.lang.String B006000101) {
		set("B006000101", B006000101);
	}

	public java.lang.String getB006000101() {
		return get("B006000101");
	}

	public void setB006000102(java.lang.String B006000102) {
		set("B006000102", B006000102);
	}

	public java.lang.String getB006000102() {
		return get("B006000102");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

}
